getPlay / getPlays lexicon
teal-fm/teal pull request #36
Opened 2024-12-31 19:01 UTC by mmattbtw

2024-12-31 19:04 UTC, mmattbtw commented on packages/lexicons/real/fm.teal.alpha.getPlay.json
> +      }
maybe include author's DID in the response?

2025-01-08 00:48 UTC, espeon commented
i dont see any issues but ill see if i can ask some ppl who know more than me

2025-01-08 03:51 UTC, espeon commented
ah shoot i need to have jetstring and amethyst use these new paths

2025-01-08 16:33 UTC, Hoid commented on packages/lexicons/real/fm/teal/alpha/actor/status.json
> +          "item": {
I'm assuming this lexicon is representing the idea of a user setting their status as, for example, listening to a certain song. In that case, what's the utility of this union? Is it just making it so that future versions of the `fm.teal.alpha.actor.status` lexicon don't have to use the fm.teal._alpha_.feed.play#record lexicon in the future (specifically the alpha version)? Or is there another reason

2025-01-08 16:34 UTC, Hoid commented on packages/lexicons/real/fm/teal/alpha/feed/defs.json
> +        "artistName": {
There's a property for a single `artistName` but then another property for `artistMbIds`, which is correctly an array. I think `artistName` should be `artistNames` plural and be an array as well, otherwise you couldn't put multiple artists in there structurally.

2025-01-08 20:40 UTC, mmattbtw commented on packages/lexicons/real/fm/teal/alpha/feed/defs.json
> +        "artistName": {
agreed

2025-01-08 20:42 UTC, espeon requested changes
good stuff, would personally go with what ezra said wrt `artistNames` and having a separate lexicon for featured album/artist/track

2025-01-08 20:42 UTC, espeon commented on packages/lexicons/real/fm.teal.alpha.getPlay.json
> +      }
never mind im being stupid, i dont think its necessary LOL

2025-01-08 20:42 UTC, espeon commented on packages/lexicons/real/fm/teal/alpha/actor/status.json
> +          "item": {
I think I was mixing up two ideas here. 

1. The purpose of this lexicon is to show the currently playing song, yes. I don't think there's a reason for the union to be here unless we plan on expanding to, say, movies and TV shows as well.

2. I was also thinking a user could put like a favorite album or artist as well as a song, but that could be served better with a separate lexicon.

2025-01-08 20:42 UTC, espeon commented on packages/lexicons/real/fm/teal/alpha/feed/defs.json
> +        "artistName": {
hmm, good point. This was originally based on the [listenbrainz submission format](https://listenbrainz.readthedocs.io/en/latest/users/json.html) which only specifies the main artist, but also the array of artist mbids as well. 

I think personally changing artistName to artistNames (or having artistNames be a separate field based on the mbids?) would be a good change, thanks!

2025-01-08 20:43 UTC, mmattbtw commented on packages/lexicons/real/fm/teal/alpha/actor/status.json
> +          "item": {
yeah, we should probably just have it be referencing the record lexicon and not be a union

2025-01-08 21:18 UTC, espeon commented on packages/lexicons/real/fm/teal/alpha/actor/status.json
> +          "item": {
well, `fm.teal.alpha.feed.defs#playView` but yeah.

2025-01-08 21:23 UTC, espeon commented
oops before we merge i need to check if it builds right

2025-01-12 06:30 UTC, espeon commented on packages/jetstring/src/index.ts
>              uri: record.commit.rkey,
okay i know this isnt related but this is rly bugging me - the db row should be 'rkey' not 'uri'

2025-01-12 06:35 UTC, espeon approved these changes
ok finally lgtm (i'm not sure how to get rid of the requested changes review?)

2025-01-13 01:05 UTC, mmattbtw reviewed
LGTM

2025-01-13 01:07 UTC, merged